name: Deploy QA Web (Vite React) to EC2

on:
  push:
    branches:
      - dev-new

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Vite App
        run: npm run build

      - name: Send dist folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.QA_EC2_HOST }}
          username: ${{ secrets.QA_EC2_USER }}
          key: ${{ secrets.QA_EC2_SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/vahanwire-website/dist"
          strip_components: 1

      - name: Restart NGINX
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_EC2_HOST }}
          username: ${{ secrets.QA_EC2_USER }}
          key: ${{ secrets.QA_EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
